# Generated by Django 5.0.6 on 2025-06-03 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stripe_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='stripe_id',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='tax',
            name='stripe_id',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
